baseurl = "https://blog.aravindhebbali.com/"
languageCode = "en-us"
title = "Aravind's Blog | R | Economics | Finance"
theme = "hugo-lithium-theme"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Online Courses"
    url = "https://rsquared-academy.thinkific.com/"   
    weight = 2

[params]
    description = "Personal blog of Aravind Hebbali, built through Hugo and blogdown."
    keywords = "aravind"
    twitterAuthor = "@hebbaliaravind"

    [params.logo]
    url = "logo.jpg"
    width = 50
    height = 50
    alt = "Aravind Hebbali"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"